# -*- coding: utf-8 -*-
"""BERT_esm1b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/sokrypton/algosb_2021/blob/main/BERT_esm1b.ipynb

install and load models
"""

import torch
import esm
import matplotlib.pyplot as plt
import numpy as np
from scipy.special import softmax
from utils import *
import sys
import pandas as pd
import gc
import glob 

print("Finished importing")

# load esm models using the esm module
model, alphabet = esm.pretrained.esm2_t33_650M_UR50D()

print("Loaded model")
# put model on GPU if available
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
model = model.to(device)
model = model.eval()
#model.args.token_dropout = False

# alphabet size
esm_alphabet_len = len(alphabet.all_toks)
esm_alphabet = "".join(alphabet.all_toks[4:24])+"-"

torch.autograd.set_detect_anomaly(True)

def read_fasta(filename):
    with open(filename, 'r') as f:
        lines = f.readlines()
    sequence = ''.join(line.strip() for line in lines if not line.startswith('>'))
    return sequence

def get_logits(seq):
  x,ln = alphabet.get_batch_converter()([("seq",seq)])[-1],len(seq)
  with torch.no_grad():
    f = lambda x: model(x)["logits"][0,1:(ln+1),4:24].cpu().numpy()
    x = x.to(device)
    logits = f(x)
    return logits

def get_masked_logits(seq, p=None, get_pll=False):
  x,ln = alphabet.get_batch_converter()([(None,seq)])[-1],len(seq)
  if p is None: p = ln
  with torch.no_grad():
    def f(x):
      fx = model(x)["logits"][:,1:(ln+1),4:24]
      return fx
    for n in range(0,ln,p):
      m = min(n+p,ln)
      x_h = torch.tile(torch.clone(x),[m-n,1])
      for i in range(m-n):
        x_h[i,n+i+1] = alphabet.mask_idx
      fx_h = f(x_h.to(device))
      for i in range(m-n):
        np.zeros((ln,20))[n+i] = fx_h[i,n+i].cpu().numpy()
  if get_pll:
    logits = np.log(softmax(np.zeros((ln,20)),-1))
    x = x.cpu().numpy()[0]
    x = x[1:(ln+1)] - 4
    return sum([logits[n,i] for n,i in enumerate(x)])
  else:
    return np.zeros((ln,20))

def get_categorical_jacobian(seq):
  # ∂in/∂out
  x,ln = alphabet.get_batch_converter()([("seq",seq)])[-1],len(seq)
  with torch.no_grad():
    f = lambda x: model(x)["logits"][...,1:(ln+1),4:24].cpu().numpy()
    fx = f(x.to(device))[0]
    x = torch.tile(x,[20,1]).to(device)
    fx_h = np.zeros((ln,20,ln,20))
    for n in range(ln): # for each position
      x_h = torch.clone(x)
      x_h[:,n+1] = torch.arange(4,24) # mutate to all 20 aa
      fx_h[n] = f(x_h)
    return fx-fx_h

def predict_and_plot(seq, name):
  print('Predicting for: '+name)
  print(seq)

  # jacobian of the model
  jac = get_categorical_jacobian(seq)
  # center & symmetrize
  for i in range(4):
    jac -= jac.mean(i,keepdims=True)
  jac = (jac + jac.transpose(2,3,0,1))/2

  L = len(seq)

  """extract contacts jacobian"""
  jac_contacts = get_contacts(jac)
  np.save(name+'_jac_contacts', jac_contacts)

  plt.figure(figsize=(10,5))
  plt.subplot(1,2,2); plt.title("jac(esm1b(msa[0]))")
  plt.savefig(name+'_jac.png')

  print("Memory before cleaning")
  print(torch.cuda.memory_summary())

  del jac 
  del jac_contacts 

  # releasing "non-releasable memory" that grows larger every loop, 
  # solution according to https://github.com/pytorch/pytorch/issues/99835
#  torch._C._cuda_clearCublasWorkspaces()
#  torch._dynamo.reset()
  gc.collect()
  torch.cuda.empty_cache()

  print("Memory after cleaning")
  print(torch.cuda.memory_summary())


input_mode = sys.argv[1]
input_file = sys.argv[2]

print(input_mode)
print(input_file)

if input_mode == "df":
  # mode of df with sequences 
  seq_tab = pd.read_table(input_file, sep='\t')
  for index, row in seq_tab.iterrows():

    chs_id = row['CHESS_ID']
    # Check if any file matching the pattern exists
    matching_files = glob.glob(f'*{chs_id}*.npy')
    
    if matching_files:
        # Skip this iteration if file exists
        print('Skipped '+chs_id)
        continue
    else:
        predict_and_plot(row['Sequence'], row['CHESS_ID'])
        gc.collect()
        torch.cuda.empty_cache()

#  for row_i in range(len(seq_tab)):
#    predict_and_plot(row['Sequence'], row['CHESS_ID']) ,axis=1)
elif input_mode == "fasta": 
  fasta = input_file
  seq = read_fasta(fasta)
  print(seq)
  predict_and_plot(seq, 'test')
